trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  - group: TestingBotSecrets  # Contains TB_KEY and TB_SECRET

steps:
# ✅ Diagnostic step (optional)
- script: |
    echo "TB_KEY: $(TB_KEY)"
    echo "TB_SECRET: $(TB_SECRET)"
    curl -I https://hub.testingbot.com/wd/hub/status
  displayName: "Verify TestingBot connection"

# ✅ Install dependencies
- script: |
    npm install -g appium appium-doctor
    appium-doctor
    npm install
  displayName: 'Install Appium & Dependencies'

# ✅ Run Android Tests (SignIn only)
- script: |
    echo "Running Android SignIn tests..."
    export PLATFORM=Android
    export DEVICE_NAME='Galaxy S21'
    export PLATFORM_VERSION='11'
    export APP='tb://38b04764b4d2ffe62247fc11'  # ✅ Replace with your real .apk TestingBot ID
    npx wdio run wdio.testingbot.conf.js
  env:
    TB_KEY: $(TB_KEY)
    TB_SECRET: $(TB_SECRET)
    NODE_OPTIONS: --dns-result-order=ipv4first
  displayName: 'Run Android SignIn Tests'

