trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: TestingBotSecrets  # Contains TB_KEY and TB_SECRET

steps:
# ✅ Diagnostic step (optional)
- script: |
    echo "TB_KEY: $(TB_KEY)"
    echo "TB_SECRET: $(TB_SECRET)"
    curl -I https://hub.testingbot.com/wd/hub/status
  displayName: "Verify TestingBot connection"

# ✅ Install dependencies
- script: |
    npm install -g appium appium-doctor
    appium-doctor
    npm ci
  displayName: 'Install Appium & Dependencies'

# ✅ Run Android Tests (SignIn only)
- script: |
    echo "Running Android SignIn tests..."
    export PLATFORM=Android
    export DEVICE_NAME='Galaxy S21'
    export PLATFORM_VERSION='11'
    export APP='tb://870185072d78c0738fcdd5f2'  # ✅ Replace with your real .apk TestingBot ID
    npx wdio run wdio.testingbot.conf.js
  env:
    TB_KEY: $(TB_KEY)
    TB_SECRET: $(TB_SECRET)
    NODE_OPTIONS: --dns-result-order=ipv4first
  displayName: 'Run Android SignIn Tests'

# ✅ Run iOS Tests (SignIn only)
- script: |
    echo "Running iOS SignIn tests..."
    export PLATFORM=iOS
    export DEVICE_NAME='iPhone 14'
    export PLATFORM_VERSION='16'
    export APP='tb://a2ac65fc662240066f6c31fd'  # ✅ Replace with your real .ipa TestingBot ID
    npx wdio run wdio.testingbot.conf.js
  env:
    TB_KEY: $(TB_KEY)
    TB_SECRET: $(TB_SECRET)
    NODE_OPTIONS: --dns-result-order=ipv4first
  displayName: 'Run iOS SignIn Tests'
