trigger: none  # Manual or triggered by another pipeline

pool:
  vmImage: ubuntu-latest

variables:
  - group: TestingBotSecrets

steps:
- script: |
    echo "TB_KEY: $(TB_KEY)"
    echo "TB_SECRET: $(TB_SECRET)"
    curl -I https://hub.testingbot.com/wd/hub/status
  displayName: "Verify TestingBot connection"

- script: |
    npm install -g appium appium-doctor
    appium-doctor
    npm install
  displayName: 'Install Appium & Dependencies'

- script: |
    echo "Running iOS SignIn tests..."
    export PLATFORM=iOS
    export DEVICE_NAME='iPhone 14'
    export PLATFORM_VERSION='16'
    export APP='tb://3be1d7c7ecf37fa7f203ebeb'  # Replace with your real .ipa TestingBot ID
    npx wdio run wdioIOS.testingbot.conf.js  --spec ./app/TestsIOS/Profile.test.js
  env:
    TB_KEY: $(TB_KEY)
    TB_SECRET: $(TB_SECRET)
    NODE_OPTIONS: --dns-result-order=ipv4first
  displayName: 'Run iOS SignIn Tests'
